### ISSUE TITLE
Error in readMat()

### ISSUE THREAD

**Issue by gullahoo** [HenrikBengtsson/R.matlab#1]
When call to readMat()  get following msg:

Error in mat5ReadTag(this) : 
  Unknown data type. Not in range [1,19]: 10540
In addition: Warning messages:

Thanks

**Comment by julievdh** [comment]
I am getting a similar error: 
data <- readMat('Data.mat')
Error in mat5ReadTag(this) : 
  Unknown data type. Not in range [1,19]: 18569
In addition: Warning messages:
1: package ‘R.matlab’ was built under R version 3.2.4 
2: In readMat5Header(this, firstFourBytes = firstFourBytes) :
  Unknown MAT version tag: 512. Will assume version 5.

R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.3 (El Capitan)

other attached packages:
[1] agricolae_1.2-3 R.matlab_3.5.0 

I saved the .mat file in multiple versions to test, but still came across the same error. Thanks!

**Comment by HenrikBengtsson** [comment]
Can you make the MAT file available to me so I can try to reproduce?

**Comment by julievdh** [comment]
Strange - sorry. Saving in '-v6' again seemed to work!

**Comment by martajak** [comment]
Hi! I have this exact same error, i.e. message: 

Trying to read MAT v5 file stream.
Error in mat5ReadTag(this) : 
  Unknown data type. Not in range [1,19]: 18569
In addition: Warning message:
In readMat5Header(this, firstFourBytes = firstFourBytes) :
  Unknown MAT version tag: 512. Will assume version 5.

I have received the Matlab file, not saved it myself, and I don't know Matlab. How did you end up fixing the problem?

**Comment by HenrikBengtsson** [comment]
Hi. I suspect you don't have a valid MAT file, or it could possibly be MAT v7.3 file which is not supported, cf. Issue #23.

Before anything else, please:

1. Make sure you run an up-to-date version of R and R.matlab.
2. Report output of `sessionInfo()` after you get that error.
3. Share exactly what your call looks like.
4. Trying adding `verbose=-100` to the `readMat()` call and report back the output.

**Comment by martajak** [comment]
Hi, thank you for the super quick reply and hepling me out! I've just had R updated, so I don't think this would be the problem. The file seemed fine when opened in Matlab (it contains 4 sets of '3d matrices'). The exact command I am trying to read it into R with is: 

**LOC100runs <- readMat("~/pazdziernik16/simulations/local_100runs_13Oct16.mat" ,verbose=-100)**

Adding the 'verbsoe' parameter produced this response:

Opens binary file: ~/pazdziernik16/simulations/local_100runs_13Oct16.mat
Trying to read MAT v5 file stream.
Reading data element...
 Reading Tag...
 Reading Tag...done
Reading data element...done: '' [NULL: ]
(...)
Reading data element...
 Reading Tag...
Error in mat5ReadTag(this) : 
  Unknown data type. Not in range [1,19]: 18569
In addition: Warning message:
In readMat5Header(this, firstFourBytes = firstFourBytes) :
  Unknown MAT version tag: 512. Will assume version 5.
 Reading Tag...done
 Binary file closed.

As for sessionInfo(), it returns:

> sessionInfo()
R version 3.3.1 (2016-06-21)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] R.matlab_3.6.0

loaded via a namespace (and not attached):
[1] tools_3.3.1       R.methodsS3_1.7.1 R.utils_2.4.0     R.oo_1.20.0  


Do you still think the file has been saved wrong? Or maybe the file is just too large for my comp to cope with? It does contain four sets of 3d matrices some 3000x3000x1000 in dimentions

**Comment by HenrikBengtsson** [comment]
First of all, the size of the file does not cause this error; the error occurs early on when it tries to parse the file header and it does not recognize it as one of the supported file header formats.  Now, if you would try to read in a 3000-by-3000-by-1000 matrix containing numeric values, that would require 3000*3000*1000*8/1000^3 = 72 GB of RAM - just for one matrix!  But, that's independent of the parsing error.

It could be that it's a MAT v7.3 file.  Install the developers version of R.matlab as (in a fresh R session):
```r
source('http://callr.org/install#HenrikBengtsson/R.matlab@develop')
```
and then retry.  If it's a MAT v7.3 file, then you'll get an informative error message saying so, e.g.
```r
> library("R.matlab")
> readMat(system.file("mat-files", "Matrix-v7.3.mat", package="R.matlab"))
Error in readMat5(con, firstFourBytes = firstFourBytes, maxLength = maxLength) : 
  Reading of MAT v7.3 files is not supported. If possible, save the data in MATLAB using 'save -V6'.
```
If that's not the case, then what does the following output:
```r
pathname <- "~/pazdziernik16/simulations/local_100runs_13Oct16.mat"
readLines(pathname, n = 1L)
```
?

**Comment by martajak** [comment]
The matrices are actually 3000x3000x100 not 1000.
After having run the source code and retrying, the same error persists:

> LOC100runs <- readMat("~/pazdziernik16/simulations/local_100runs_13Oct16.mat",verbose=-100)
> Opens binary file: ~/pazdziernik16/simulations/local_100runs_13Oct16.mat
> Trying to read MAT v5 file stream.
> Reading data element...
>  Reading Tag...
>  Reading Tag...done
> Reading data element...done: '' [NULL: ]
...
> Reading data element...
>  Reading Tag...
>  Reading Tag...done
> Reading data element...done: '' [NULL: ]
> Reading data element...
>  Reading Tag...
> Error in mat5ReadTag(this) : 
>   Unknown data type. Not in range [1,19]: 18569
> In addition: Warning message:
> In readMat5Header(this, firstFourBytes = firstFourBytes) :
>   Unknown MAT version tag: 512. Will assume version 5.
>  Reading Tag...done
>  Binary file closed.

This id the output from the command you suggested:
> pathname <- "~/pazdziernik16/simulations/local_100runs_13Oct16.mat"
> readLines(pathname, n = 1L)
[1] "MATLAB 7.3 MAT-file, Platform: PCWIN64, Created on: Fri Oct 14 03:03:16 2016 HDF5 schema 1.00 .                     "
Warning message:
In readLines(pathname, n = 1L) : line 1 appears to contain an embedded nul

**Comment by HenrikBengtsson** [comment]
So, this is clearly a MAT v7.3 file;  I'm surprised your update didn't give:
```r
> readMat(pathname)
Error in readMat5(con, firstFourBytes = firstFourBytes, maxLength = maxLength) : 
  Reading of MAT v7.3 files is not supported. If possible, save the data in MATLAB using 'save -V6'.
```
Are you sure you installed the develop version in a fresh R session and restarted R before trying again?

Regardless, as the error message says, MAT v7.3 files [are not supported](https://github.com/HenrikBengtsson/R.matlab/issues/20) and you need to find alternatively.

**Comment by martajak** [comment]
Is saving the file in a different Matlab version the only way of loading it
in to R then?

2016-10-16 20:27 GMT+01:00 Henrik Bengtsson <notifications@github.com>:

**Comment by HenrikBengtsson** [comment]
Not a different Matlab version, but to a different MAT file format
version.  See ?readMat and the error message already mentioned here. But,
yes, you need to resave it in Matlab. /H

**Comment by martajak** [comment]
Thank you. I had the Matlab file saved as v5 and it works now. 
In terms of referring to the content of the file now, there are the four 3d matrices (3000x3000x100). I would like to have four lists of 100 elements (i.e. the 2d matrices), is this obtainable? If so, how could I do that? Thanks again!

**Comment by HenrikBengtsson** [comment]
Hi, good to hear that you can now read in your data in R.

The question on how to split up a 3000x3000x1000 matrix X into a list of 100 3000x3000 matrices is independent of R.matlab and is better asked on the R-help mailing list.  I simply don't have the bandwidth to answer such questions too - I hope you understand.

**Comment by martajak** [comment]
Sure, will refer back to R. Thank you!

**Comment by chandu1234567** [comment]
Hi Martajak & Henrik , i too have a similar problem . Couldn't able to open a .mat file  in R . i followed all your conversation , but i missed something in that version change. can u guys help me plz?

i don't know anything about MATLAB , but i got a file with .mat ext and i need to use in R for further analysis . 

plz Help .
