### ISSUE TITLE
Error During Matlab packages for R installation

### ISSUE THREAD

**Issue by liupan539649** [HenrikBengtsson/R.matlab#11]
Hello everybody, 

I encountered two errors during Installation of matlab packages for R.(install.packages("R.matlab"))

1. Error in read.table(file = file, header = header, sep = sep, quote = quote,  : more column than column Name.
2. Fehler: Zeile beginnend mit '<!DOCTYPE html PUBLI ...' ist fehlformatiert (Translate: Error: Row begins with '<!DOCTYPE html PUBLI ...' is false formatted.)

Can anybody fix them?

**Comment by liupan539649** [comment]
I have fixed them. Thanks for your Attention...

**Comment by HenrikBengtsson** [comment]
Good. FYI, I replied a few hours ago explaining this is an error
independent of R.matlab, but reply was never send/recorded.

**Comment by liupan539649** [comment]
ah...I got...thank you all the same. By the way, do u know how to save data calculated in R as Mat file to a path in my Computer? Thank you.

**Comment by liupan539649** [comment]
You are right. It is Independent of R. It is the Problem of my Computer...
