### ISSUE TITLE
setFunction  cannot be run

### ISSUE THREAD

**Issue by ynhuruc** [HenrikBengtsson/R.matlab#16]
In the help document, there are errors in  the results of  the example as follows:

setFunction(matlab, "          \
+   function [win,aver]=dice(B)  \
+   %Play the dice game B times  \
+             gains=[-1,2,-3,4,-5,6];      \
+             plays=unidrnd(6,B,1);        \
+             win=sum(gains(plays));       \
+             aver=win/B;                  \
+             ");

Error in writeFieldNames(names(structure), maxLength = 32) : 
  4 arguments passed to .Internal(nchar) which requires 3

**Comment by HenrikBengtsson** [comment]
It looks like you're running outdated versions of R and/or R.matlab and
possibly other packages. If so, make sure to update.

**Comment by ynhuruc** [comment]
Thanks for your reply. As you said, the problem is the outdated version of R.
