### ISSUE TITLE
Help Understanding Java Exception during readByte

### ISSUE THREAD

**Issue by stefanavey** [HenrikBengtsson/R.matlab#26]
I'm sporadically getting a MatlabException with the following error message:

    [2015-09-14 16:10:26] Exception: MatlabException: Failed to evaluate expression '[result,xcentr,ycentr]=csimpls_fuse_lasso5(x_train, y_train, L,lasso, fuse, 'k',N);'.                                                                                                                                                                      
              
    at #05. readResult.Matlab(this)
    - readResult.Matlab() is in environment 'R.matlab'

    at #04. readResult(this)
    - readResult() is in environment 'R.matlab'

    at #03. evaluate.Matlab(matlab, paste0("[result,xcentr,ycentr]=", simplsFunc,
                                       "(x_train, y_train, L,lasso, fuse, 'k', N);"))
    - evaluate.Matlab() is in environment 'R.matlab'

    at #02. evaluate(matlab, paste0("[result,xcentr,ycentr]=", simplsFunc,
                                "(x_train, y_train, L,lasso, fuse, 'k', N);"))
    - evaluate() is in environment 'R.matlab'

    at #01. cv.nrsplsda(x = x_train, yCat = y_train, simplsFunc = simplsFunc,
                      foldl = foldl, matlab = matlab, gname = gname, K = K, fuseParam = fuseParam,
                      lassoParam = lassoParam, classifier = "logistic", scale.x = FALSE,
                      scale.y = FALSE, n.core = NULL, verbose = TRUE)
    - cv.nrsplsda() is in environment 'R_GlobalEnv'

    Error: MatlabException: Failed to evaluate expression '[result,xcentr,ycentr]=csimpls_fuse_lasso5(x_train, y_train, L,lasso, fuse, 'k', N);'.                                             
    Execution halted
    Error using MatlabServer (line 163)
    Java exception occurred:
    java.io.EOFException
            at java.io.DataInputStream.readByte(Unknown Source)

The Matlab code it is evaluating runs a loop and I can see in the output that 2 out of 4 loop iterations complete before it fails.  Now I can run the same exact command interactively with the same parameters and I don't get an error (all four loop iterations complete).  When I run my R script from the command line the error happens about 50% of the time on the same evaluate command but with different parameters.

My question is: **How can I look more into what the problem is because the Java exception error is cryptic and I don't understand what is happening on line 163 of Matlabserver.m?**

        cmd = readByte(is);

I'm using the most recent stable version of R.matlab and here is the output of `sessionInfo()`

    R version 3.2.1 (2015-06-18)
    Platform: x86_64-unknown-linux-gnu (64-bit)
    Running under: Red Hat Enterprise Linux Server release 6.2 (Santiago)

    locale:
    [1] LC_CTYPE=en_US       LC_NUMERIC=C         LC_TIME=en_US
    [4] LC_COLLATE=en_US     LC_MONETARY=en_US    LC_MESSAGES=en_US
    [7] LC_PAPER=en_US       LC_NAME=C            LC_ADDRESS=C
    [10] LC_TELEPHONE=C       LC_MEASUREMENT=en_US LC_IDENTIFICATION=C

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base

    other attached packages:
    [1] igraph_1.0.1   R.matlab_3.2.0

    loaded via a namespace (and not attached):
    [1] compiler_3.2.1    magrittr_1.5      tools_3.2.1       R.methodsS3_1.7.0
    [5] R.utils_2.1.0     R.oo_1.19.0

For Matlab:

                            < M A T L A B (R) >
                  Copyright 1984-2014 The MathWorks, Inc.
                    R2014a (8.3.0.532) 64-bit (glnxa64)
                             February 11, 2014

**Comment by HenrikBengtsson** [comment]
> My question is: How can I look more into what the problem is because the Java exception error is cryptic and I don't understand what is happening on line 163 of Matlabserver.m?

The key to understand the error message is probably in the fact that a `java.io.EOFException` was thrown.  This indicates that the connection from with MATLAB/Java reads has been closed - probably by the other end (R/R.matlab).  Other than this, it's not easy to say without being able to reproduce it or narrow down a minimal reproducible example.

> The Matlab code it is evaluating runs a loop and I can see in the output that 2 out of 4 loop iterations complete before it fails. Now I can run the same exact command interactively with the same parameters and I don't get an error (all four loop iterations complete). When I run my R script from the command line the error happens about 50% of the time on the same evaluate command but with different parameters.

Are you saying that you:
* get the error if you run `Rscript matlab.R`
* don't get the error if you run `source('matlab.R')` from within R?

**Comment by stefanavey** [comment]
To your last point, not exactly.  

- I sometimes get the error running `Rscript matlab.R --vanilla`
- I don't get the error when running the commands interactively (like `source('matlab.R')` except that I don't have to run the whole thing because I know what my parameter combinations were when the error happened so I just put in those parameters instead of looping through all combinations).  This was just to test whether the parameter combinations were to blame.

**Comment by HenrikBengtsson** [comment]
One hypothesis I have is that when you run `Rscript matlab.R`, the script and the R session itself finishes before the MATLAB server has had a chance to complete.  When R exits it calls finalizers on R.matlab that cleanups after itself and in this process it also closes connections.  So, if it finishes before MATLAB had a chance to read from the connection, it _might_ be that we get this error.  When you run in an interactive session, the R session does not close and the R.matlab finalizers are not triggered.

I'm just guessing here, but you could try to add a very long `Sys.sleep(<seconds>)` at the end of your `matlab.R` script to see if it makes a difference.  It has to be long enough for you to make sure things complete on the MATLAB server side.

Related, do you explicitly `close(matlab)` at the end of `matlab.R`?  If not, that might prevent the problem.

I would be helpful to see you complete `matlab.R` script.

**Comment by stefanavey** [comment]
Henrik, thank you for your comments.  I don' think R is finishing before Matlab because this happens in the middle of a loop and the R process shouldn't be finishing.  I do explicitly call `close(matlab)` at the end of the script.

I'll work on trying to get a MWE script together.

**Comment by HenrikBengtsson** [comment]
> I don' think R is finishing before Matlab because this happens in the middle of a loop and the R process shouldn't be finishing.

Unless there's an error signaled on the R side causing it to exit.  This error could in turn happen because the MATLAB server sends something that confuses R.matlab.  However, if there's an error, you should be able to see it from the (stderr) output.

**Comment by stefanavey** [comment]
Based on what you said about the signal to exit, I added `nohup` to the beginning of the command and it finished successfully.  Not sure what might be telling R or Matlab to exit.  I will continue to test this and close if this fixes the issue.  Thanks for your help!

**Comment by HenrikBengtsson** [comment]
Thanks for following up.  Yes, the fact that running with `nohup` indicates something else sends the interrupt/terminate signal to the R or MATLAB.  Maybe a timeout limit in an interactive ssh session?  Maybe on the client, maybe on the server side.

**Comment by stefanavey** [comment]
Yes well I thought that fixed it but today tried the same thing twice and get the same old error (even with nohup). Any other ideas of what to try to get at the root of this?
