### ISSUE TITLE
Error in mat5ReadArrayFlags(this) :   Unknown array type (class). Not in [1,16]: 17

### ISSUE THREAD

**Issue by yakzan** [HenrikBengtsson/R.matlab#32]
Trying to read a .mat (saved on R2015b, with no arguments given to the save function) file gives the error:

Error in mat5ReadArrayFlags(this) : 
  Unknown array type (class). Not in [1,16]: 17

**Comment by HenrikBengtsson** [comment]
Need more information in order to reproduce, e.g. `traceback()`, `sessionInfo()`, minimal problematic MAT file and MATLAB code created the MAT file.

FYI, R.matlab 3.4.0 had undocumented array type 16 ("function") recognized, cf. Issue #28.  That yet another undocumented type appears (17) is interesting.

**Comment by yakzan** [comment]
Sure, here they are. 

(BTW, this is after source('http://callr.org/install#HenrikBengtsson/R.matlab@develop'))

traceback()
7: stop("Unknown array type (class). Not in [1,", NBR_OF_KNOWN_ARRAY_FLAGS, 
       "]: ", class)
6: mat5ReadArrayFlags(this)
5: mat5ReadMiMATRIX(this, tag)
4: readMat5DataElement(this)
3: readMat5(con, firstFourBytes = firstFourBytes, maxLength = maxLength)
2: readMat.default("~/sensorData/watchData/smoking/Dec-22/Dec-22.mat", 
       verbose = TRUE)
1: readMat("~/sensorData/watchData/smoking/Dec-22/Dec-22.mat", verbose = TRUE)

sessioninfo():
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.3 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] R.matlab_3.4.0-9000

loaded via a namespace (and not attached):
 [1] httr_1.1.0         R6_2.1.2           tools_3.2.3        withr_1.0.1        curl_0.9.6        
 [6] memoise_1.0.0      R.methodsS3_1.7.1  git2r_0.13.1       digest_0.6.9       R.utils_2.2.0-9000
[11] devtools_1.10.0    R.oo_1.20.0

**Comment by yakzan** [comment]
One quick observation: 
The error occurs when the saved workspace contains objects like model (ClassificationPartitionedModel) and datetime; I tested with both types in different files, and both resulted in the same error.

**Comment by HenrikBengtsson** [comment]
Do need MATLAB script and MAT file in order to look into this.

**Comment by yakzan** [comment]
Sure, the zip file contains the .mat files, and the script is below:
[matFiles.zip](https://github.com/HenrikBengtsson/R.matlab/files/143275/matFiles.zip)

```
md = datetime('16-Dec-2015 22:23:23');
save('~/dateTest.mat');

clear all
load carsmall;
X = [Acceleration,Weight];
T = [0 0 0;1 0 0;0 1 0;1 1 0;0 2 0];
mdl = fitlm(X,MPG,T);
save('~/modelTest.mat');

clear mdl
save('~/allTest.mat');
```

So, both dateTest.mat and modelTest fail with the error before, and allTest.mat is just parsed perfectly.

**Comment by HenrikBengtsson** [comment]
FYI, with a fresh MATLAB v7.14.0.739 (2012) I get:
```matlab
>> md = datetime('16-Dec-2015 22:23:23');
Undefined function 'datetime' for input arguments of type 'char'.

>> clear all
>> load carsmall;
>> X = [Acceleration,Weight];
>> T = [0 0 0;1 0 0;0 1 0;1 1 0;0 2 0];
>> mdl = fitlm(X,MPG,T);
Undefined function 'fitlm' for input arguments of type 'double'.
```
I guess this could be because the MATLAB version I have access to is rather old.  FYI, I haven't been using MATLAB for many years so assume zero savviness on my end.

I probably can work with the MAT files as is without having to reproduce them myself, but any more information on what type of objects `md` and `mdl` are would be helpful.

**Comment by yakzan** [comment]
Indeed, datetime is introduced in 2014b, and fitlm in 2013b. 

Here are the outputs for the `who` command: 

```
  Name      Size            Bytes  Class       Attributes

  md        1x1               121  datetime              

  mdl       1x1             16168  LinearModel
```

http://www.mathworks.com/help/stats/fitlm.html
http://www.mathworks.com/help/matlab/ref/datetime.html

**Comment by HenrikBengtsson** [comment]
I've added minimalistic support for array type/class 17.  It parses such elements basically by reading most of it as a raw byte stream and then continue with the rest of the MAT file.  This should at least allow you to read the MAT file and make use of all other types of elements in the file.

Try it out by installing:
```r
source("http://callr.org/install#HenrikBengtsson/R.matlab@develop")
```

Some more comments:  The parsed data element contains the name `MCOS`, e.g.
```r
> pathname <- system.file("mat-files", "datetime,arraytype=17-v5.mat", package="R.matlab")
> data <- R.matlab::readMat(pathname)
> str(data)
List of 3
 $ MCOS: raw [1:8] 64 61 74 65 ...
 $     : int [1:6, 1] -587202560 2 1 1 1 1
 $     : int [1, 1:1056] 0 1 73 77 0 0 0 0 14 0 ...
 - attr(*, "header")=List of 3
  ..$ description: chr "MATLAB 5.0 MAT-file, Platform: MACI64, Created on: Tue Feb 23 21:27:34 2016                                         Ó"
  ..$ version    : chr "5"
  ..$ endian     : chr "little"

```
It could be that this indicates that the array type 17 stands for "MATLAB Class Object System (MCOS)", cf. [Undocumented Matlab, Introduction to UDD, February 2011](http://undocumentedmatlab.com/blog/introduction-to-udd).  @yakzan, if you can find out more information about this, it might be possible to pull out a bit more useful information out of this.

**Comment by yakzan** [comment]
Works just great (also with different kind of classification models). 

I'll keep an eye on those relatively new types.

**Comment by yakzan** [comment]
I checked the SciPy implementation here: https://github.com/scipy/scipy/blob/v0.17.0/scipy/io/matlab/mio5_params.py

Their guess is based on an older octave discussion (but the link is dead by now) and on the matrix.h file. 

The R2015b matrix.h file on the other hand, is a little bit different, as far as I can see though, with the `mxVOID_CLASS` at the 6th row and `mxLOGICAL_CLASS` taking the 4th, possibly contrary to the documentation:

```
typedef enum
{
    mxUNKNOWN_CLASS = 0,
    mxCELL_CLASS,
    mxSTRUCT_CLASS,
    mxLOGICAL_CLASS,
    mxCHAR_CLASS,
    mxVOID_CLASS,
    mxDOUBLE_CLASS,
    mxSINGLE_CLASS,
    mxINT8_CLASS,
    mxUINT8_CLASS,
    mxINT16_CLASS,
    mxUINT16_CLASS,
    mxINT32_CLASS,
    mxUINT32_CLASS,
    mxINT64_CLASS,
    mxUINT64_CLASS,
    mxFUNCTION_CLASS,
    mxOPAQUE_CLASS,
    mxOBJECT_CLASS, /* keep the last real item in the list */
#if defined(_LP64) || defined(_WIN64)
    mxINDEX_CLASS = mxUINT64_CLASS,
#else
    mxINDEX_CLASS = mxUINT32_CLASS,
#endif
    /* TEMPORARY AND NASTY HACK UNTIL mxSPARSE_CLASS IS COMPLETELY ELIMINATED */
    mxSPARSE_CLASS = mxVOID_CLASS /* OBSOLETE! DO NOT USE */
}
mxClassID;

```

**Comment by HenrikBengtsson** [comment]
Thanks for these references.  I [tracked down](https://github.com/scipy/scipy/pull/5929/files) the Octave Maintainers discussion thread 'saveing/loading symbol table of annymous functions', April-May 2007:

* https://lists.gnu.org/archive/html/octave-maintainers/2007-04/msg00031.html
* https://lists.gnu.org/archive/html/octave-maintainers/2007-05/msg00032.html

**Comment by HenrikBengtsson** [comment]
@yakzan, is the "R2015b matrix.h file" distributed by MATLAB or did you get it from somewhere else?  Do you know if it's available online?

**Comment by yakzan** [comment]
It's the one of my installation, @HenrikBengtsson. Do you need the whole file?

**Comment by HenrikBengtsson** [comment]
Not really, I wanted to know for sure that those symbols/names are the ones that MATLAB uses internally (modulo the discrepancies between that file and their docs).  I'll rename to `mxOPAQUE_CLASS` in R.matlab (now just `mxUNKNOWN17_CLASS`).

**Comment by yakzan** [comment]
Thanks for all your effort, this is a great tool @HenrikBengtsson!

**Comment by HenrikBengtsson** [comment]
Now on CRAN - https://cran.r-project.org/web/packages/R.matlab/
